### ISSUE TITLE
Use standard R package structure and workflow

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#1]
Thanks for the nice pioneer work on VSCode R Debugger!

It would be nice the package is structured in a standard way and use standard workflow of R package authoring, then it would be much easier to collaborate on and work with.

The standard package strcture is that the repo root is the package root that contains `DESCRIPTION` and `NAMESPACE` which are necesary files for the package, both should not be git-ignored.

This will make all kinds of devtools, languageserver, CI to work out of the box.

If you don't mind, I could help restructure the project so that it is standard and will be much easier for contributors to work together.

**Comment by ManuelHentschel** [comment]
That would be great :)
I'm rather new to R package development, so please don't hesitate to fix any "odd" design decisions that might interfere with standard dev tools etc.
