### ISSUE TITLE
No support for R version 4.0.2

### ISSUE THREAD

**Issue by Jieli12** [ManuelHentschel/vscDebugger#110]
Hi All, 

When I install vscDebugger package, it shows package ‘vscDebugger’ is not available (for R version 4.0.2).
Would you please figure it out?

**Comment by ManuelHentschel** [comment]
The package is currently not on CRAN and therefore cannot be installed with `install.packages('vscDebugger')`.

If you are using the VS Code extension you can try entering the command `rdebugger.updateRPackage` in the command pallette (`ctrl+shift+p`).

If this does not work, you can install the extension from the assets found [here](https://github.com/ManuelHentschel/VSCode-R-Debugger/releases).

Does this work for you?

**Comment by Jieli12** [comment]
Thank you very much. It works well.

**Comment by jasonmorkel** [comment]
Thanks - this worked for me too!

**Comment by w8665763** [comment]
Error in unpackPkgZip(pkgs[i], pkgnames[i], lib, libs_only, lock, quiet) : 
  package 'vscDebugger' not installed because it is not built for UCRT
Calls: install.packages -> .install.winbinary -> unpackPkgZip

**Comment by andreagithub97** [comment]
download no zip compressed but tar 
 https://github.com/ManuelHentschel/VSCode-R-Debugger/releases/download/v0.4.7/vscDebugger_0.4.7.tar.gz 
and install it from menu packages - install package from local file
