### ISSUE TITLE
getwd changes working directory?

### ISSUE THREAD

**Issue by bersbersbers** [ManuelHentschel/vscDebugger#122]
This R file works fine, printing `/tmp` twice:
```
setwd("/tmp")
print(getwd())
print(getwd())
quit()
```

But debugging it using the extension outputs this, note the last line:
```
Starting R session...
R Startup:
{
  "path": "/home/bers/R-4.0.2/bin/R",
  "args": [
    "--ess",
    "--quiet",
    "--interactive",
    "--no-save"
  ],
  "cwd": "/home/bers/proj1"
}
Initialize Arguments:
{
  "clientID": "vscode",
  "clientName": "Visual Studio Code",
  "adapterID": "R-Debugger",
  "pathFormat": "path",
  "linesStartAt1": true,
  "columnsStartAt1": true,
  "supportsVariableType": true,
  "supportsVariablePaging": true,
  "supportsRunInTerminalRequest": true,
  "locale": "en-us",
  "supportsProgressReporting": true,
  "supportsInvalidatedEvent": true,
  "threadId": 1,
  "extensionVersion": "0.3.1",
  "rStrings": {
    "prompt": "<#v\\s\\c>",
    "continue": "<##v\\s\\c>",
    "startup": "<v\\s\\c\\R\\STARTUP>",
    "libraryNotFound": "<v\\s\\c\\LIBRARY\\NOT\\FOUND>",
    "packageName": "vscDebugger"
  },
  "jsonHost": "localhost",
  "jsonPort": 44353,
  "sinkHost": "localhost",
  "sinkPort": 45121
}
Launch Arguments:
{
  "name": "R Debugger",
  "type": "R-Debugger",
  "request": "launch",
  "debugMode": "workspace",
  "workingDirectory": "/home/bers/proj2",
  "allowGlobalDebugging": true,
  "file": "/home/bers/proj2/figures/src/script.R",
  "mainFunction": "main",
  "__sessionId": "4ec70f25-e131-4bd1-b97f-63681d768f2c"
}
.vsc.debugSource("/home/bers/proj2/figures/src/script.R")
[1] "/tmp"
[1] "/home/bers/proj2"

```

**Comment by ManuelHentschel** [comment]
Thanks for the issue and the detailed information!
The problem was with `.vsc.print` (which by default overwrites `print`) and should be fixed by the linked PR.

On a side note:
You can also specify a working directory in the launch config entry `"workingDirectory"`, which defaults to the workspace folder.
However, since the R process is launched without knowing the launch config, an `.Rprofile` file will always be run from the workspace folder (if present).

**Comment by ManuelHentschel** [comment]
The master branch is quite far ahead the last release (v0.3.1), to get just the fix to this problem you can install from the branch [FixWdV0.3.1](https://github.com/ManuelHentschel/vscDebugger/tree/FixWdV0.3.1), which is based on the that release.

**Comment by bersbersbers** [comment]
Thanks!

May I ask, out of curiosity, what this line does?
```R
tmpwd <- getwd()
```
https://github.com/ManuelHentschel/vscDebugger/pull/123/files#diff-6ef54cf4fec0f3dc09d412bcb5dbb03356d8c40e1b7af1b754449c917be5d0ddR112

`tmpwd` is overwritted just after that.

**Comment by ManuelHentschel** [comment]
I added that line for the case that `setwd()` fails, since then `tmpwd` would not have a value and `setwd(tmpwd)` in the `finally` expression would fail.

The function definitely looks weird, a more elegant solution would probably be
``` r
    ret <- tryCatch(
      {
        tmpwd <- getwd()
        setwd(wd)
        normalizePath(path, winslash, mustWork)
      },
      error = function(e) path,
      finally = setwd(tmpwd)
    )
```

**Comment by tdeenes** [comment]
A common idiom is to use `on.exit()` right after the `setwd()` call if one wants to change the working directory temporarily.  E.g.
```r
setwd(wd)
on.exit(setwd(tmpwd)) # or on.exit(setwd(tmpwd), add = TRUE)
```

**Comment by ManuelHentschel** [comment]
Thanks, changed it again :)
