### ISSUE TITLE
Create pkgdown website for vscDebugger

### ISSUE THREAD

**Issue by gvelasq** [ManuelHentschel/vscDebugger#148]
I'd be happy to propose a PR for a {pkgdown} website, if it would be helpful.

**Comment by ManuelHentschel** [comment]
Thanks for the offer! That would definitely be a welcome contribution :)

**Comment by gvelasq** [comment]
Great! I'll work on it this week.

**Comment by ManuelHentschel** [comment]
Thanks for the PR!

There is some additional information in https://github.com/ManuelHentschel/VSCode-R-Debugger/blob/master/configuration.md and the readme of https://github.com/ManuelHentschel/VSCode-R-Debugger, do you have any suggestion how these could be integrated in a user-friendly way?

**Comment by gvelasq** [comment]
Happy to help, @ManuelHentschel. Regarding the additional information, I can think of a few ways:

1. Move information from into the vscDebugger `README.md` so it will be rendered into the pkgdown landing page. The downside is that the `README.md` will become very long.
2. Create vignettes from the additional content you mentioned. For example, https://github.com/ManuelHentschel/VSCode-R-Debugger could be converted into a 'Getting Started' vignette for vscDebugger, and https://github.com/ManuelHentschel/VSCode-R-Debugger/blob/master/configuration.md could be converted into a 'Configuration Details' vignette.
3. Some combination of 1 and 2.

**Comment by ManuelHentschel** [comment]
Sounds good. I'm not very familiar with vignettes etc. so I'd merge this PR as is, and try to implement your ideas later, together with some general improvements of the documentation. If you have more experience with this subject, I'd of course be happy to merge any further improvements as well :)
