### ISSUE TITLE
Feature request: support .Last.value

### ISSUE THREAD

**Issue by bersbersbers** [ManuelHentschel/vscDebugger#164]
**Describe the bug**
It seems `.Last.value` is not supported.

**To Reproduce**
Debug the code. Compare with `Rscript`, e.g.
```bash
echo -e "4 * 5\nprint(.Last.value)" | Rscript -
```

**Your R code**
```
4 * 5
print(.Last.value)
```

**Expected behavior**
```
[1] 20
```

**Actual behavior**
```
[1] TRUE
```

**Comment by ManuelHentschel** [comment]
There's `.ans` in the global environment, which is roughly the equivalent of `base::.Last.value`. We could rename this to `.Last.value` or make the name user configurable. Would this work for you or is there more to the normal `.Last.value` that you use?

**Comment by bersbersbers** [comment]
I did not know about `.ans` and would be fine using that, but I have trouble getting that to work reliably.
```
echo -e "4 * 5\nprint(globalenv()$.ans)" | Rscript -
[1] 20
NULL
```
It does work interactively sometimes, but not reliably.

To explain where I am coming from: I often copy and paste `ggplot2` examples which usually end with a `ggplot2::ggplot()` call that is not assigned to any variable. Since I'm working remotely, X11 is painfully slow, so I usually store the plot as an existing PNG file using a some predefined function, and have that refreshed in a viewer. It appears that I can simply use `ggplot2::last_plot()` for that.

So I leave it up to you to support (or not) `.Last.value` - my expectation was that anything I can write into an R script and run in `Rscript` should work in the debugger, but of course my understanding of the internals are very limited.

**Comment by ManuelHentschel** [comment]
> I did not know about `.ans` and would be fine using that, but I have trouble getting that to work reliably.

`.ans` is only available in the debugger (as a substitute/alternative for `.Last.value`), so it is not expected to work with Rscript. In the debugger, `.ans` should always be assigned the result of the last evaluation entered in the debug console.



> my expectation was that anything I can write into an R script and run in `Rscript` should work in the debugger

In general, the debugger is designed to mimick `source()` which behaves a little different from `Rscript` in this regard. Afaik, `Rscript` runs each command as if it was entered into stdin (separately), but `source()` treats the entire file contents like a single command.

**Comment by bersbersbers** [comment]
> In general, the debugger is designed to mimick `source()` which behaves a little different from `Rscript` in this regard. Afaik, `Rscript` runs each command as if it was entered into stdin (separately), but `source()` treats the entire file contents like a single command.

That makes a lot of sense. In fact, while
```bash
echo -e "4 * 5\nprint(.Last.value)" | Rscript -
```
outputs
```
[1] 20
[1] 20
```
,
```bash
echo -e "4 * 5\nprint(.Last.value)" > bug.R && echo "source('bug.R')" | Rscript -
```
outputs just
```
NULL
```
So I don't see an big issue with `.Last.value` returning `NULL` as well, although it would be convenient. #165 looks very useful.

Thanks for the explanation!
