### ISSUE TITLE
Weird Error when debugging mlr3oml

### ISSUE THREAD

**Issue by sebffischer** [ManuelHentschel/vscDebugger#174]
**Describe the bug**
Debugging [mlr3oml](https://github.com/mlr-org/mlr3oml) does not work but gives the error that is printed indefinitely:

```
Error in `[[.R6`(list, entry) : 
  R6 class RootNode/MetaNode/Node/R6 does not have slot 'variablesReference'!
8: `[[.R6`(list, entry)
7: list[[entry]]
6: lget(self, "variablesReference", 0)
5: session$rootNode$findChildNode(list(findBy = "varRef", varRef = varRef))
4: variablesRequest(response, args, request)
3: .vsc.dispatchRequest(obj)
2: .vsc.handleJson(json)
1: vscDebugger::.vsc.listenForJSON(timeout = -1)
```

**To Reproduce**
1. Clone [mlr3oml](https://github.com/mlr-org/mlr3oml) into __~/__
1. Open __mlr3oml__ as a project in VSCode
1. Start "Debug R-Package". 
1. The error as shown above arises and is printed indefinitely. 

**Your Launch config**
Default configurations for both cases, i.e. "Debug R-Package". 

**Expected behavior**
I expect to not get the error message and be able to debug the package. 

**Actual behavior**
The error message, as shown above, is printed indefinitely in the Debug Console. 

**Desktop (please complete the following information):**
 - OS: WSL: Ubuntu-20.04 (via VS-Code Remotes Extension) 
 - R Version: 4.1.1
 - vscDebugger Version: 0.4.7
 - vscode-r-debugger Version: 0.4.7

**Additional context**
The above-described procedure works for other packages. 
Also only running __load_all()__ works for __mlr3oml__.

**Comment by ManuelHentschel** [comment]
Does https://github.com/ManuelHentschel/vscDebugger/commit/ce8f2489ecc45750a1142af5fb202c5e6a651448 change anything?

**Comment by sebffischer** [comment]
Sorry, I forgot to answer and switched to neovim shortly after.
