### ISSUE TITLE
Use in R 3.4.2

### ISSUE THREAD

**Issue by d-que** [ManuelHentschel/vscDebugger#175]
Hi all,

I am trying to install the package version 0.4.7 on an R installation of version 3.4.2. 

When I try to use the VS Code command as suggested in issue #110, I receive 

 `Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror 
Calls: install.packages -> contrib.url 
Execution halted`

I have R6 (2.5.1) and jsonlite (1.6) both installed.

Is this a version issue or is there anything I can do?

Many thanks in advance!

**Comment by ManuelHentschel** [comment]
You can also install the package from source using `remotes::install_github` (or by cloning this repo and running `devtools::install`). Does that work for you?

**Comment by d-que** [comment]
Hi Manuel,

It worked finally though RTools.
