### ISSUE TITLE
`internalLoadAll`: can not set the parent environment of a namespace

### ISSUE THREAD

**Issue by kongdd** [ManuelHentschel/vscDebugger#183]
R version: v4.2.1
System: win10

```R
vscDebugger:::internalLoadAll(".")
```

```R
i Loading vscDebugger
Error in `parent.env<-`(`*tmp*`, value = <environment>) : 
  can not set the parent environment of a namespace
2: `parent.env<-`(`*tmp*`, value = <environment>) at overwrites.R#281
```

https://github.com/ManuelHentschel/vscDebugger/blob/master/R/overwrites.R#L273-L280

**Comment by grishin** [comment]
Must be related to https://stat.ethz.ch/pipermail/r-devel/2014-October/069931.html ? I also confirm that debugging of packages doesn't work on r 4.2.1 in win10.

![image](https://user-images.githubusercontent.com/3284017/197847682-bf191d09-1e3e-4cb5-bf20-63cd64d53ad6.png)
