### ISSUE TITLE
Error: Please install the R package "vscDebugger"

### ISSUE THREAD

**Issue by michael-bentz** [ManuelHentschel/vscDebugger#185]
After installing the latest version with _R Debugger > update or install the required R package_ I get "Please install the R package "vscDebugger".

<img width="1856" alt="Screenshot 2022-11-16 at 1 52 16 PM" src="https://user-images.githubusercontent.com/75623654/202267926-99985943-79c9-443c-a41b-06e60e46c88a.png">

**To Reproduce**
1. Install R Debugger from extensions tab
2. Create test file `test.R`
3. Set breakpoint
4. Debug with "Debug R-File" profile listed below.
5. See error

**Your R code**
print("Hello world")

**Your Launch config**
If applicable, the launch config that causes the bug. E.g.:
``` json
        {
            "type": "R-Debugger",
            "request": "launch",
            "name": "Debug R-File",
            "debugMode": "file",
            "workingDirectory": "${workspaceFolder}",
            "file": "${file}",
            "allowGlobalDebugging": true
        }
```
**Desktop (please complete the following information):**
 - OS: Ventura 13.0 (M1 mac)
 - R Version: 4.2.2
 - vscDebugger Version: 0.4.7
 - vscode-r-debugger Version: 0.4.7

Repeating the same steps above but installing with
```R
install.packages("https://github.com/ManuelHentschel/vscDebugger/releases/download/v0.4.7/vscDebugger_0.4.7.tgz", repos = NULL, type = "mac.binary")
devtools::install_github("ManuelHentschel/vscDebugger", force = TRUE)
```
results in the same error as https://github.com/ManuelHentschel/vscDebugger/issues/131.

**Comment by ManuelHentschel** [comment]
There have been some changes to the communication between the vscode-extension and the R package in version v.0.5.0., but also some issues with the Github actions, causing the packages to not be released correctly. To make things worse, there seem to have been some changes to how R handles UTF-8 encoding internally recently (see some of the posts on [the R blog](https://blog.r-project.org/)). I just released v0.5.1 for both the vscode-Extension and the R package. At least for me, they work fine with R v0.4.1, but sometimes cause issues on R v0.4.2.
