### ISSUE TITLE
vscDebugger don't work for arm64?

### ISSUE THREAD

**Issue by dune0310421** [ManuelHentschel/vscDebugger#193]
My Macbook is supported by M2 chip, and I have installed vscDebugger. But when I tried running my code, it showed me ""Please install the R package "vscDebugger"", and I got an error:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so, 0x0006): tried: '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so' (no such file), '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```
It seems that the package cannot work for arm64.  Are there packages for arm64 that I didn't find, and if not, will there be packages for that? Or is it a problem that have nothing to do with x86/arm?

**Comment by eitsupi** [comment]
I think you need to install from source.
For example with this function `remotes::install_github("ManuelHentschel/vscDebugger@*release")`

**Comment by dune0310421** [comment]
> I think you need to install from source. For example with this function `remotes::install_github("ManuelHentschel/vscDebugger@*release")`

Thanks! This way indeed works!
