### ISSUE TITLE
Rename repo to package name

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#2]
The current name of this repo is a bit vague, looks like it is the R package behind vscode-R extension (In fact, we use simple in-place R scripts instead of a package to make the bundle easier) rather than VSCode-R-Debugger. It would be nice if this repo could be renamed to match the package name `vscDebugger` as part of the standard practice.

**Comment by ManuelHentschel** [comment]
Makes sense. While we're at it: would you keep the name `vscDebugger` or do you think a different name would be more fitting? `vscDebuggerSupport`? `vsCodeDebugSupport`? ...?

**Comment by renkun-ken** [comment]
I think `vscDebugger` looks perfectly fine and it is an R package so it is clear enough to mean it is an R package to support VSCode Debugger (for R).

BTW, working with a long package name could be a bit painful :)
