### ISSUE TITLE
Remove pryr dependency

### ISSUE THREAD

**Issue by tdeenes** [ManuelHentschel/vscDebugger#34]
Thanks for the package, looks really promising!

I do not think it is a good idea to import **pryr** which is not actively maintained any more (it is explicitly stated as being superseded by other packages). Moreover, you call its internal (unexported) functions which actually do nothing more than simply wrap base R's `findVar` (src/main/envir.c) and the corresponding function, e.g., TYPEOF, PRVALUE etc. from Rinternals.h.

If you agree I will create a PR which removes the **pryr** dependency without sacrificing the promise-related functionalities of **vscDebugger**.

**Comment by renkun-ken** [comment]
Thanks for noticing the pryr being superseded by other packages.

Are you planning to write some simple `.c` to replace those pryr calls? It would be nice if we keep minimal dependency.

**Comment by ManuelHentschel** [comment]
This dependency has been bothering me a bit actually, so any improvements are very welcome!

**Comment by tdeenes** [comment]
> Are you planning to write some simple `.c` to replace those pryr calls? It would be nice if we keep minimal dependency.

Yes, exactly. No Rcpp, it is an overkill for this task. I will try to do it within a week.

**Comment by ManuelHentschel** [comment]
In https://github.com/ManuelHentschel/vscDebugger/pull/41 I added some support for missing function arguments and '...' but did not manage to get the arguments supplied in '...' without forcing any promises (as would happen by just calling `list(...)` in the correct environment). The promise tools from **pryr** also didn't quite work, but supplied at least some information.
Do you think this would possible using C?

**Comment by tdeenes** [comment]
@ManuelHentschel , `...` can be expanded without evaluating the arguments with a "hidden" trick in R, see PR #46.

**Comment by tdeenes** [comment]
@ManuelHentschel 
I have a working implementation for this issue; which branch shall I base the PR on?

**Comment by ManuelHentschel** [comment]
`develop` please :)
