### ISSUE TITLE
Consider tinytest instead of testthat

### ISSUE THREAD

**Issue by tdeenes** [ManuelHentschel/vscDebugger#35]
Currently the package lacks proper unit tests anyway, so I think it is better to switch from **testthat** to **tinytest** at this point. The latter testing framework is much more lightweight and has many compelling features. 

I am happy to create a PR if you agree.

**Comment by ManuelHentschel** [comment]
I don't have much experience with either of those, so I wouldn't mind switching to **tinytest**.
Thanks for your help!

**Comment by renkun-ken** [comment]
Have't used tinytest yet. Looks very lightweight and it's good. testthat's dependencies are just too heavy.

**Comment by tdeenes** [comment]
OK, I will create the PR early next week.
