### ISSUE TITLE
Use attach list to hide overridden functions

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#8]
In RStudio, many backend functions are put into a list and the list is attached so that it appears in the search path.

For example, in a fresh RStudio session, `tools:rstudio` contains the attached list of functions:

```
> search()
 [1] ".GlobalEnv"        "tools:rstudio"     "package:stats"     "package:graphics"  "package:grDevices"
 [6] "package:utils"     "package:datasets"  "package:methods"   "Autoloads"         "package:base"
```

If we use similar method, the overridden functions will not be shown in the global environment to be mixed up with user defined functions:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/4662568/83081591-a66d6a00-a0b3-11ea-97e8-271843fae208.png">

Following is a minimal example:

```r
attach(list(
  print = function(x, ...) {
    base::cat("new print:\n")
    base::print(x, ...)
  }
), name = "tools:vscDebugger")
search()
ls()

m <- rnorm(10)
print(m)
```

```
> attach(list( 
    print = function(x, ...) { 
      base::cat("new print:\n") 
      base::print(x, ...) 
    } 
  ), name = "tools:vscDebugger")                                                          
The following object is masked from package:base:

    print


> search()                                                                                 
 [1] ".GlobalEnv"         "tools:vscDebugger" "package:stats"      "package:graphics"  
 [5] "package:grDevices"  "package:utils"      "package:datasets"   "package:methods"   
 [9] "Autoloads"          "package:base"      

> ls()                                                                                     
character(0)

> m <- rnorm(10)                                                                           

> print(m)                                                                                 
new print:
 [1]  0.4019033 -0.5384726 -0.7945924  0.2734667  0.1027051 -1.2539160  0.7839037
 [8]  1.0921911  2.3513295  0.8522005
```

**Comment by ManuelHentschel** [comment]
You're right, having these functions in the .GlobalEnv does look a bit clumsy...
I think it's important that the assignments made by the debugger (outside of its own namespace/environment) are transparent to the user, but your suggestion looks like a good compromise between transparency and tidiness.

**Comment by renkun-ken** [comment]
>My best solution so far is to assign print <- vscDebugger::.vsc.print in the extension, but this also causes print to be overwritten for any calls from the .GlobalEnv.

I don't quite understand. Isn't that what we want?

**Comment by ManuelHentschel** [comment]
What bothers me is that you have to alter the code of the extension and include explicit references to code from vscDebugger. Which can cause problems when the same code is run from the terminal/RStudio

**Comment by ManuelHentschel** [comment]
But it's not a very urgent issue, since you can simply use the default `print` and `cat` methods and just not see the filename/line
