### ISSUE TITLE
infos[["childVars"]][[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#97]
With the latest master of both vscDebugger and VSCode-R-Debugger, I could reproduce the following error:

1. Debug R-Function `objects.R`
2. `browser()` in `fun(x, y, ...)` is hit.
3. Expand `<environment: R_GlobalEnv>` in the variables view
4. Click `.__C__Employee` or `.__C__Person` created by `setClass` functions in the source code.
5. The following error occurs:

```
Error in infos[["childVars"]][[i]] : subscript out of bounds
```

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/4662568/91648922-516d3580-eaa0-11ea-8ce4-2a30168a8518.png">

**Comment by ManuelHentschel** [comment]
Thanks for catching that!

There were actually two underlying problems:
1. The VarInfo `S4` is also applied to `S4 classRepresentations` and here the `VarInfo$childVars()` intended for S4 instances does not work properly. I fixed this by setting the childVars of `S4 classRepresentations` to `list()`. If you think there are sensible childvars that should be shown, feel free to add them (or tell me what you have in mind and I add them)
2. The stackTree was not able to gracefully handle a difference between promised `nChildVars()` and the actual `childVars`. I fixed this by replacing 'missing' childVars with a warning. This warning should ideally never occur with the default VarInfos but is definitely better than crashing...

**Comment by ManuelHentschel** [comment]
On a sidenote:
I find it a bit easier to check the varInfos by launching objects.R with `Debug R-File` and then viewing the global variables in the dummy frame "Global Workspace". Your approach works just as well, I just wanted to mention this option, since it's quite easy to miss the "Global Workspace" frame and I couldn't figure out a clean way to make it show automatically.

**Comment by renkun-ken** [comment]
The fix makes good sense to me. Thanks!

>I find it a bit easier to check the varInfos by launching objects.R with Debug R-File and then viewing the global variables in the dummy frame "Global Workspace". Your approach works just as well, I just wanted to mention this option, since it's quite easy to miss the "Global Workspace" frame and I couldn't figure out a clean way to make it show automatically.

I tried it and it works nicely! Didn't notice there's a `Global Workspace`.
